name=XMPP_StartTLS
version=1.0.0
author=Oleg Isabekov
maintainer=Oleg Isabekov <olegisabekov@gmail.com>
sentence=An Arduino library for jabber server with TLS
paragraph=
category=Sensors
url=
architectures=*
